spring:
  profiles:
    active: dev
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  rabbitmq:
    host: 192.168.64.128
    port: 5672
    username: guest
    password: guest
zuul:
  routes:
    service-a:
      path: /service/**
      serviceId: ribbon-service
management:
 security:
  enabled: false
